import { thaiWords } from './captions.mjs';

const clean=value=>String(value||'').toLocaleLowerCase('th').replace(/[\p{P}\p{S}\s]+/gu,'');
export const wordTokens=(text,language='th')=>thaiWords(text,language).map(word=>clean(word.text)).filter(Boolean);
export function editDistance(left,right){const a=[...left],b=[...right],row=Array.from({length:b.length+1},(_,index)=>index);for(let i=1;i<=a.length;i++){let diagonal=row[0];row[0]=i;for(let j=1;j<=b.length;j++){const above=row[j],cost=a[i-1]===b[j-1]?0:1;row[j]=Math.min(row[j]+1,row[j-1]+1,diagonal+cost);diagonal=above}}return row[b.length]}
export function wordErrorRate(reference,hypothesis,language='th'){const expected=wordTokens(reference,language),actual=wordTokens(hypothesis,language);return expected.length?editDistance(expected,actual)/expected.length:(actual.length?1:0)}
export function characterErrorRate(reference,hypothesis){const expected=[...clean(reference)],actual=[...clean(hypothesis)];return expected.length?editDistance(expected,actual)/expected.length:(actual.length?1:0)}
export function medianBoundaryError(referenceWords,hypothesisWords){const candidates=[];for(const expected of referenceWords||[]){const actual=(hypothesisWords||[]).find(word=>clean(word.text)===clean(expected.text)&&!word.__matched);if(!actual)continue;actual.__matched=true;candidates.push(Math.abs(actual.start-expected.start),Math.abs(actual.end-expected.end))}for(const word of hypothesisWords||[])delete word.__matched;if(!candidates.length)return null;candidates.sort((a,b)=>a-b);const middle=Math.floor(candidates.length/2);return candidates.length%2?candidates[middle]:(candidates[middle-1]+candidates[middle])/2}
export function wordsOutsideSpeech(words,speechRegions,minimumOverlap=.45){return(words||[]).filter(word=>{const duration=Math.max(.001,word.end-word.start),overlap=Math.max(0,...(speechRegions||[]).map(region=>Math.min(word.end,region.end)-Math.max(word.start,region.start)));return overlap/duration<minimumOverlap})}
export function evaluateFixture(fixture){const reference=fixture.reference||{},baseline=fixture.baseline||{},candidate=fixture.candidate||{},speechRegions=fixture.speechRegions||candidate.speechRegions||[];return{baselineWer:wordErrorRate(reference.text,baseline.text,fixture.language),candidateWer:wordErrorRate(reference.text,candidate.text,fixture.language),baselineCer:characterErrorRate(reference.text,baseline.text),candidateCer:characterErrorRate(reference.text,candidate.text),medianBoundaryError:medianBoundaryError(reference.words||[],candidate.words||[]),silentWordCount:wordsOutsideSpeech(candidate.words||[],speechRegions).length}}
